version: '3.8'

services:
  app:
    image: abdillah953/sipancet:1.0.0  # Pulling from Docker Hub
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel
    depends_on:
      - db
    entrypoint: >
      sh -c "php artisan migrate --force || true && php-fpm"

  webserver:
    image: nginx:stable-alpine-perl
    container_name: nginx_webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel
    depends_on:
      - app

  db:
    image: mysql:latest
    container_name: sipancet
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sipancet
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
